# Generated by Django 5.1.1 on 2024-12-08 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='activo',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.TextField(choices=[('CASA', 'Casa'), ('DEPARTAMENTO', 'Departamento'), ('CABAÑA', 'Cabaña'), ('OFICINA', 'Oficina'), ('BODEGA', 'Bodega'), ('OTRO', 'Otro')], default='Otro', max_length=20),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='usuario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('NO_DISPONIBLE', 'No_Disponible')], default='Disponible', max_length=20),
        ),
    ]
