/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 160004 (160004)
 Source Host           : localhost:5432
 Source Catalog        : gestion_inmuebles
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160004 (160004)
 File Encoding         : 65001

 Date: 10/12/2024 15:36:49
*/


-- ----------------------------
-- Table structure for auth_user
-- ----------------------------
DROP TABLE IF EXISTS "public"."auth_user";
CREATE TABLE "public"."auth_user" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "password" varchar(128) COLLATE "pg_catalog"."default" NOT NULL,
  "last_login" timestamptz(6),
  "is_superuser" bool NOT NULL,
  "username" varchar(150) COLLATE "pg_catalog"."default" NOT NULL,
  "first_name" varchar(150) COLLATE "pg_catalog"."default" NOT NULL,
  "last_name" varchar(150) COLLATE "pg_catalog"."default" NOT NULL,
  "email" varchar(254) COLLATE "pg_catalog"."default" NOT NULL,
  "is_staff" bool NOT NULL,
  "is_active" bool NOT NULL,
  "date_joined" timestamptz(6) NOT NULL
)
;

-- ----------------------------
-- Records of auth_user
-- ----------------------------
INSERT INTO "public"."auth_user" VALUES (1, 'pbkdf2_sha256$870000$Ukpnj7CkeJrnhTUKjdT7Xe$8BZvWdoe0GLcpLpiT82V5Cuw9stDIzQjz/jnFcTgIjE=', '2024-12-08 21:33:41.204709-03', 't', 'usuario', '', '', 'admin@gestioninmobiliaria.cl', 't', 't', '2024-12-08 20:44:28.106971-03');
INSERT INTO "public"."auth_user" VALUES (4, 'pbkdf2_sha256$870000$x6Hek8SiRwTb9d7aUqc36N$dTqWuDC23wu7RHUEJ2hHIP+8126JcdOu1pc1x+3yshI=', '2024-12-10 01:02:09.639139-03', 'f', 'arrendatario2', 'Zalatiel', 'Sandoval', 'test2@test.cl', 'f', 't', '2024-12-10 00:59:20.243124-03');
INSERT INTO "public"."auth_user" VALUES (3, 'pbkdf2_sha256$870000$SAbGvRBrJajt3rlErpKnh1$tDRbow4CjWtEHCrDsLUf98jYYMXTGsU/L9W4y5SNf98=', '2024-12-10 15:02:05.435639-03', 'f', 'arrendador1', 'Julio', 'Mendez', 'test@test.cl', 'f', 't', '2024-12-08 21:42:17.19909-03');
INSERT INTO "public"."auth_user" VALUES (2, 'pbkdf2_sha256$870000$BmZBN5yhEmHi41gfycY1WV$LQjd+TzYckM92WeAzZvZkhu4HJ4Ikja3H/jjMWIDsqk=', '2024-12-10 15:11:35.465875-03', 'f', 'arrendatario1', 'Camila Andrea', 'Sandoval', 'camibarrera@gmail.com', 'f', 't', '2024-12-08 21:10:29.82509-03');

-- ----------------------------
-- Auto increment value for auth_user
-- ----------------------------
SELECT setval('"public"."auth_user_id_seq"', 4, true);

-- ----------------------------
-- Indexes structure for table auth_user
-- ----------------------------
CREATE INDEX "auth_user_username_6821ab7c_like" ON "public"."auth_user" USING btree (
  "username" COLLATE "pg_catalog"."default" "pg_catalog"."varchar_pattern_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table auth_user
-- ----------------------------
ALTER TABLE "public"."auth_user" ADD CONSTRAINT "auth_user_username_key" UNIQUE ("username");

-- ----------------------------
-- Primary Key structure for table auth_user
-- ----------------------------
ALTER TABLE "public"."auth_user" ADD CONSTRAINT "auth_user_pkey" PRIMARY KEY ("id");
