/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 160004 (160004)
 Source Host           : localhost:5432
 Source Catalog        : gestion_inmuebles
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160004 (160004)
 File Encoding         : 65001

 Date: 10/12/2024 15:36:43
*/


-- ----------------------------
-- Table structure for auth_permission
-- ----------------------------
DROP TABLE IF EXISTS "public"."auth_permission";
CREATE TABLE "public"."auth_permission" (
  "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "content_type_id" int4 NOT NULL,
  "codename" varchar(100) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of auth_permission
-- ----------------------------
INSERT INTO "public"."auth_permission" VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO "public"."auth_permission" VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO "public"."auth_permission" VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO "public"."auth_permission" VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO "public"."auth_permission" VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO "public"."auth_permission" VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO "public"."auth_permission" VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO "public"."auth_permission" VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO "public"."auth_permission" VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO "public"."auth_permission" VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO "public"."auth_permission" VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO "public"."auth_permission" VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO "public"."auth_permission" VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO "public"."auth_permission" VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO "public"."auth_permission" VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO "public"."auth_permission" VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO "public"."auth_permission" VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO "public"."auth_permission" VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO "public"."auth_permission" VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO "public"."auth_permission" VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO "public"."auth_permission" VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO "public"."auth_permission" VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO "public"."auth_permission" VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO "public"."auth_permission" VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO "public"."auth_permission" VALUES (25, 'Can add comuna', 7, 'add_comuna');
INSERT INTO "public"."auth_permission" VALUES (26, 'Can change comuna', 7, 'change_comuna');
INSERT INTO "public"."auth_permission" VALUES (27, 'Can delete comuna', 7, 'delete_comuna');
INSERT INTO "public"."auth_permission" VALUES (28, 'Can view comuna', 7, 'view_comuna');
INSERT INTO "public"."auth_permission" VALUES (29, 'Can add region', 8, 'add_region');
INSERT INTO "public"."auth_permission" VALUES (30, 'Can change region', 8, 'change_region');
INSERT INTO "public"."auth_permission" VALUES (31, 'Can delete region', 8, 'delete_region');
INSERT INTO "public"."auth_permission" VALUES (32, 'Can view region', 8, 'view_region');
INSERT INTO "public"."auth_permission" VALUES (33, 'Can add tipo inmueble', 9, 'add_tipoinmueble');
INSERT INTO "public"."auth_permission" VALUES (34, 'Can change tipo inmueble', 9, 'change_tipoinmueble');
INSERT INTO "public"."auth_permission" VALUES (35, 'Can delete tipo inmueble', 9, 'delete_tipoinmueble');
INSERT INTO "public"."auth_permission" VALUES (36, 'Can view tipo inmueble', 9, 'view_tipoinmueble');
INSERT INTO "public"."auth_permission" VALUES (37, 'Can add inmueble', 10, 'add_inmueble');
INSERT INTO "public"."auth_permission" VALUES (38, 'Can change inmueble', 10, 'change_inmueble');
INSERT INTO "public"."auth_permission" VALUES (39, 'Can delete inmueble', 10, 'delete_inmueble');
INSERT INTO "public"."auth_permission" VALUES (40, 'Can view inmueble', 10, 'view_inmueble');
INSERT INTO "public"."auth_permission" VALUES (41, 'Can add user profile', 11, 'add_userprofile');
INSERT INTO "public"."auth_permission" VALUES (42, 'Can change user profile', 11, 'change_userprofile');
INSERT INTO "public"."auth_permission" VALUES (43, 'Can delete user profile', 11, 'delete_userprofile');
INSERT INTO "public"."auth_permission" VALUES (44, 'Can view user profile', 11, 'view_userprofile');
INSERT INTO "public"."auth_permission" VALUES (45, 'Can add solicitud', 12, 'add_solicitud');
INSERT INTO "public"."auth_permission" VALUES (46, 'Can change solicitud', 12, 'change_solicitud');
INSERT INTO "public"."auth_permission" VALUES (47, 'Can delete solicitud', 12, 'delete_solicitud');
INSERT INTO "public"."auth_permission" VALUES (48, 'Can view solicitud', 12, 'view_solicitud');
INSERT INTO "public"."auth_permission" VALUES (49, 'Can add gestion solicitud', 13, 'add_gestionsolicitud');
INSERT INTO "public"."auth_permission" VALUES (50, 'Can change gestion solicitud', 13, 'change_gestionsolicitud');
INSERT INTO "public"."auth_permission" VALUES (51, 'Can delete gestion solicitud', 13, 'delete_gestionsolicitud');
INSERT INTO "public"."auth_permission" VALUES (52, 'Can view gestion solicitud', 13, 'view_gestionsolicitud');

-- ----------------------------
-- Auto increment value for auth_permission
-- ----------------------------
SELECT setval('"public"."auth_permission_id_seq"', 52, true);

-- ----------------------------
-- Indexes structure for table auth_permission
-- ----------------------------
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "public"."auth_permission" USING btree (
  "content_type_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Uniques structure for table auth_permission
-- ----------------------------
ALTER TABLE "public"."auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");

-- ----------------------------
-- Primary Key structure for table auth_permission
-- ----------------------------
ALTER TABLE "public"."auth_permission" ADD CONSTRAINT "auth_permission_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table auth_permission
-- ----------------------------
ALTER TABLE "public"."auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "public"."django_content_type" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
