/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 160004 (160004)
 Source Host           : localhost:5432
 Source Catalog        : gestion_inmuebles
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160004 (160004)
 File Encoding         : 65001

 Date: 10/12/2024 15:37:20
*/


-- ----------------------------
-- Table structure for django_migrations
-- ----------------------------
DROP TABLE IF EXISTS "public"."django_migrations";
CREATE TABLE "public"."django_migrations" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "app" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "name" varchar(255) COLLATE "pg_catalog"."default" NOT NULL,
  "applied" timestamptz(6) NOT NULL
)
;

-- ----------------------------
-- Records of django_migrations
-- ----------------------------
INSERT INTO "public"."django_migrations" VALUES (1, 'contenttypes', '0001_initial', '2024-12-08 18:58:14.027686-03');
INSERT INTO "public"."django_migrations" VALUES (2, 'auth', '0001_initial', '2024-12-08 18:58:14.841713-03');
INSERT INTO "public"."django_migrations" VALUES (3, 'admin', '0001_initial', '2024-12-08 18:58:14.949949-03');
INSERT INTO "public"."django_migrations" VALUES (4, 'admin', '0002_logentry_remove_auto_add', '2024-12-08 18:58:15.003947-03');
INSERT INTO "public"."django_migrations" VALUES (5, 'admin', '0003_logentry_add_action_flag_choices', '2024-12-08 18:58:15.014945-03');
INSERT INTO "public"."django_migrations" VALUES (6, 'contenttypes', '0002_remove_content_type_name', '2024-12-08 18:58:15.119945-03');
INSERT INTO "public"."django_migrations" VALUES (7, 'auth', '0002_alter_permission_name_max_length', '2024-12-08 18:58:15.151947-03');
INSERT INTO "public"."django_migrations" VALUES (8, 'auth', '0003_alter_user_email_max_length', '2024-12-08 18:58:15.16895-03');
INSERT INTO "public"."django_migrations" VALUES (9, 'auth', '0004_alter_user_username_opts', '2024-12-08 18:58:15.184978-03');
INSERT INTO "public"."django_migrations" VALUES (10, 'auth', '0005_alter_user_last_login_null', '2024-12-08 18:58:15.236949-03');
INSERT INTO "public"."django_migrations" VALUES (11, 'auth', '0006_require_contenttypes_0002', '2024-12-08 18:58:15.240949-03');
INSERT INTO "public"."django_migrations" VALUES (12, 'auth', '0007_alter_validators_add_error_messages', '2024-12-08 18:58:15.275948-03');
INSERT INTO "public"."django_migrations" VALUES (13, 'auth', '0008_alter_user_username_max_length', '2024-12-08 18:58:15.356947-03');
INSERT INTO "public"."django_migrations" VALUES (14, 'auth', '0009_alter_user_last_name_max_length', '2024-12-08 18:58:15.434948-03');
INSERT INTO "public"."django_migrations" VALUES (15, 'auth', '0010_alter_group_name_max_length', '2024-12-08 18:58:15.485946-03');
INSERT INTO "public"."django_migrations" VALUES (16, 'auth', '0011_update_proxy_permissions', '2024-12-08 18:58:15.517949-03');
INSERT INTO "public"."django_migrations" VALUES (17, 'auth', '0012_alter_user_first_name_max_length', '2024-12-08 18:58:15.662947-03');
INSERT INTO "public"."django_migrations" VALUES (18, 'gestion_inmuebles', '0001_initial', '2024-12-08 18:58:16.000312-03');
INSERT INTO "public"."django_migrations" VALUES (19, 'sessions', '0001_initial', '2024-12-08 18:58:16.191704-03');
INSERT INTO "public"."django_migrations" VALUES (20, 'gestion_inmuebles', '0002_remove_inmueble_activo_inmueble_tipo_inmueble_and_more', '2024-12-08 19:34:18.68027-03');
INSERT INTO "public"."django_migrations" VALUES (21, 'gestion_inmuebles', '0003_solicitud', '2024-12-08 20:41:54.331078-03');
INSERT INTO "public"."django_migrations" VALUES (22, 'gestion_inmuebles', '0004_gestionsolicitud', '2024-12-09 11:46:17.357405-03');

-- ----------------------------
-- Auto increment value for django_migrations
-- ----------------------------
SELECT setval('"public"."django_migrations_id_seq"', 22, true);

-- ----------------------------
-- Primary Key structure for table django_migrations
-- ----------------------------
ALTER TABLE "public"."django_migrations" ADD CONSTRAINT "django_migrations_pkey" PRIMARY KEY ("id");
