/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 160004 (160004)
 Source Host           : localhost:5432
 Source Catalog        : gestion_inmuebles
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160004 (160004)
 File Encoding         : 65001

 Date: 10/12/2024 15:37:39
*/


-- ----------------------------
-- Table structure for gestion_inmuebles_gestionsolicitud
-- ----------------------------
DROP TABLE IF EXISTS "public"."gestion_inmuebles_gestionsolicitud";
CREATE TABLE "public"."gestion_inmuebles_gestionsolicitud" (
  "id" int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1
),
  "nombre" varchar(100) COLLATE "pg_catalog"."default" NOT NULL,
  "estado" varchar(20) COLLATE "pg_catalog"."default" NOT NULL,
  "arrendatario_id" int4 NOT NULL,
  "id_solicitud_id" int8 NOT NULL,
  "inmueble_id" int4 NOT NULL
)
;

-- ----------------------------
-- Records of gestion_inmuebles_gestionsolicitud
-- ----------------------------

-- ----------------------------
-- Auto increment value for gestion_inmuebles_gestionsolicitud
-- ----------------------------
SELECT setval('"public"."gestion_inmuebles_gestionsolicitud_id_seq"', 1, false);

-- ----------------------------
-- Indexes structure for table gestion_inmuebles_gestionsolicitud
-- ----------------------------
CREATE INDEX "gestion_inmuebles_gestionsolicitud_arrendatario_id_0d9fbb47" ON "public"."gestion_inmuebles_gestionsolicitud" USING btree (
  "arrendatario_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);
CREATE INDEX "gestion_inmuebles_gestionsolicitud_id_solicitud_id_0984a176" ON "public"."gestion_inmuebles_gestionsolicitud" USING btree (
  "id_solicitud_id" "pg_catalog"."int8_ops" ASC NULLS LAST
);
CREATE INDEX "gestion_inmuebles_gestionsolicitud_inmueble_id_dbb61e4c" ON "public"."gestion_inmuebles_gestionsolicitud" USING btree (
  "inmueble_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table gestion_inmuebles_gestionsolicitud
-- ----------------------------
ALTER TABLE "public"."gestion_inmuebles_gestionsolicitud" ADD CONSTRAINT "gestion_inmuebles_gestionsolicitud_pkey" PRIMARY KEY ("id");

-- ----------------------------
-- Foreign Keys structure for table gestion_inmuebles_gestionsolicitud
-- ----------------------------
ALTER TABLE "public"."gestion_inmuebles_gestionsolicitud" ADD CONSTRAINT "gestion_inmuebles_ge_arrendatario_id_0d9fbb47_fk_auth_user" FOREIGN KEY ("arrendatario_id") REFERENCES "public"."auth_user" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."gestion_inmuebles_gestionsolicitud" ADD CONSTRAINT "gestion_inmuebles_ge_id_solicitud_id_0984a176_fk_gestion_i" FOREIGN KEY ("id_solicitud_id") REFERENCES "public"."gestion_inmuebles_solicitud" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "public"."gestion_inmuebles_gestionsolicitud" ADD CONSTRAINT "gestion_inmuebles_ge_inmueble_id_dbb61e4c_fk_gestion_i" FOREIGN KEY ("inmueble_id") REFERENCES "public"."gestion_inmuebles_inmueble" ("id_inmueble") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
