/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 160004 (160004)
 Source Host           : localhost:5432
 Source Catalog        : gestion_inmuebles
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160004 (160004)
 File Encoding         : 65001

 Date: 10/12/2024 15:37:53
*/


-- ----------------------------
-- Table structure for gestion_inmuebles_region
-- ----------------------------
DROP TABLE IF EXISTS "public"."gestion_inmuebles_region";
CREATE TABLE "public"."gestion_inmuebles_region" (
  "id_region" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "nombre_region" varchar(300) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of gestion_inmuebles_region
-- ----------------------------
INSERT INTO "public"."gestion_inmuebles_region" VALUES (1, 'Arica y Parinacota');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (2, 'Tarapacá');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (3, 'Antofagasta');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (4, 'Atacama');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (5, 'Coquimbo');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (6, 'Valparaíso');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (7, 'O''Higgins');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (8, 'Maule');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (9, 'Ñuble');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (10, 'Biobío');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (11, 'La Araucanía');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (12, 'Los Ríos');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (13, 'Los Lagos');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (14, 'Aysén');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (15, 'Magallanes');
INSERT INTO "public"."gestion_inmuebles_region" VALUES (16, 'Metropolitana');

-- ----------------------------
-- Auto increment value for gestion_inmuebles_region
-- ----------------------------
SELECT setval('"public"."gestion_inmuebles_region_id_region_seq"', 16, true);

-- ----------------------------
-- Primary Key structure for table gestion_inmuebles_region
-- ----------------------------
ALTER TABLE "public"."gestion_inmuebles_region" ADD CONSTRAINT "gestion_inmuebles_region_pkey" PRIMARY KEY ("id_region");
