/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 160004 (160004)
 Source Host           : localhost:5432
 Source Catalog        : gestion_inmuebles
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160004 (160004)
 File Encoding         : 65001

 Date: 10/12/2024 15:37:33
*/


-- ----------------------------
-- Table structure for gestion_inmuebles_comuna
-- ----------------------------
DROP TABLE IF EXISTS "public"."gestion_inmuebles_comuna";
CREATE TABLE "public"."gestion_inmuebles_comuna" (
  "id_comuna" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "nombre_comuna" varchar(250) COLLATE "pg_catalog"."default" NOT NULL,
  "id_region_id" int4 NOT NULL
)
;

-- ----------------------------
-- Records of gestion_inmuebles_comuna
-- ----------------------------
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (1, 'Arica', 1);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (2, 'Camarones', 1);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (3, 'Putre', 1);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (4, 'General Lagos', 1);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (5, 'Iquique', 2);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (6, 'Alto Hospicio', 2);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (7, 'Camiña', 2);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (8, 'Colchane', 2);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (9, 'Huara', 2);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (10, 'Pica', 2);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (11, 'Pozo Almonte', 2);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (12, 'Antofagasta', 3);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (13, 'Calama', 3);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (14, 'Mejillones', 3);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (15, 'San Pedro de Atacama', 3);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (16, 'Sierra Gorda', 3);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (17, 'Taltal', 3);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (18, 'Ollagüe', 3);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (19, 'Tocopilla', 3);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (20, 'María Elena', 3);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (21, 'Copiapó', 4);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (22, 'Caldera', 4);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (23, 'Tierra Amarilla', 4);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (24, 'Vallenar', 4);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (25, 'Freirina', 4);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (26, 'Huasco', 4);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (27, 'Alto del Carmen', 4);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (28, 'Chañaral', 4);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (29, 'Diego de Almagro', 4);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (30, 'La Serena', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (31, 'Coquimbo', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (32, 'La Higuera', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (33, 'Paihuano', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (34, 'Vicuña', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (35, 'Illapel', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (36, 'Canela', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (37, 'Los Vilos', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (38, 'Salamanca', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (39, 'Combarbalá', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (40, 'Monte Patria', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (41, 'Punitaqui', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (42, 'Río Hurtado', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (43, 'Ovalle', 5);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (44, 'Valparaíso', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (45, 'Viña del Mar', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (46, 'Concón', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (47, 'Quintero', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (48, 'Puchuncaví', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (49, 'San Antonio', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (50, 'El Quisco', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (51, 'El Tabo', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (52, 'Algarrobo', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (53, 'Cartagena', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (54, 'Los Andes', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (55, 'San Felipe', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (56, 'Catemu', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (57, 'Llaillay', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (58, 'Panquehue', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (59, 'Putaendo', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (60, 'Rinconada', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (61, 'San Esteban', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (62, 'La Calera', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (63, 'La Cruz', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (64, 'Limache', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (65, 'Nogales', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (66, 'Olmué', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (67, 'Quillota', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (68, 'Casa Blanca', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (69, 'Santo Domingo', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (70, 'Hijuelas', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (71, 'Quilpué', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (72, 'Villa Alemana', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (73, 'La Ligua', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (74, 'Cabildo', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (75, 'Zapallar', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (76, 'Papudo', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (77, 'Petorca', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (78, 'Calle Larga', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (79, 'Santa María', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (80, 'Rapa Nui', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (81, 'Juan Fernandez', 6);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (82, 'Rancagua', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (83, 'Machalí', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (84, 'San Fernando', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (85, 'Rengo', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (86, 'Graneros', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (87, 'San Vicente de Tagua Tagua', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (88, 'Pichilemu', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (89, 'Pichidegua', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (90, 'Chimbarongo', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (91, 'Coltauco', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (92, 'Peumo', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (93, 'Las Cabras', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (94, 'Navidad', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (95, 'Chépica', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (96, 'Nancagua', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (97, 'Pumanque', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (98, 'Doñihue', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (99, 'La Estrella', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (100, 'Litueche', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (101, 'Marchihue', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (102, 'Paredones', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (103, 'Peralillo', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (104, 'Quinta de Tilcoco', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (105, 'Santa Cruz', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (106, 'Olivar', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (107, 'Codegua', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (108, 'Requínoa', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (109, 'Malloa', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (110, 'Coinco', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (111, 'Palmilla', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (112, 'Placilla', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (113, 'Lolol', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (114, 'Moztazal', 7);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (115, 'Talca', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (116, 'Curicó', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (117, 'Linares', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (118, 'Molina', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (119, 'San Javier', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (120, 'Villa Alegre', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (121, 'Cauquenes', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (122, 'Colbún', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (123, 'San Clemente', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (124, 'Río Claro', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (125, 'Pelarco', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (126, 'Pencahue', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (127, 'Constitución', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (128, 'Curepto', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (129, 'Empedrado', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (130, 'Chanco', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (131, 'Sagrada Familia', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (132, 'Hualañé', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (133, 'Teno', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (134, 'Licantén', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (135, 'Vichuquén', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (136, 'Retiro', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (137, 'Maule', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (138, 'Romeral', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (139, 'Rauco', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (140, 'Yerbas Buenas', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (141, 'Longaví', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (142, 'Parral', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (143, 'Pelluhue', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (144, 'San Rafael', 8);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (145, 'Chillán', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (146, 'Chillán Viejo', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (147, 'Bulnes', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (148, 'El Carmen', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (149, 'Pemuco', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (150, 'Quirihue', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (151, 'Ránquil', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (152, 'Ninhue', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (153, 'San Carlos', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (154, 'San Fabián', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (155, 'San Nicolás', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (156, 'Yungay', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (157, 'Pinto', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (158, 'Coihueco', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (159, 'Ñiquén', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (160, 'San Ignacio', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (161, 'Trehuaco', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (162, 'Quillón', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (163, 'Coelemu', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (164, 'Portezuelo', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (165, 'Cobquecura', 9);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (166, 'Antuco', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (167, 'Arauco', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (168, 'Cabrero', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (169, 'Cañete', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (170, 'Chiguayante', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (171, 'Concepción', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (172, 'Coronel', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (173, 'Hualpén', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (174, 'Hualqui', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (175, 'Laja', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (176, 'Lebu', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (177, 'Los Ángeles', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (178, 'Mulchén', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (179, 'Nacimiento', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (180, 'Negrete', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (181, 'Penco', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (182, 'San Pedro de la Paz', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (183, 'San Rosendo', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (184, 'Santa Bárbara', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (185, 'Santa Juana', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (186, 'Talcahuano', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (187, 'Tomé', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (188, 'Tucapel', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (189, 'Yumbel', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (190, 'Los Álamos', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (191, 'Florida', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (192, 'Lota', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (193, 'Contulmo', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (194, 'Curanilahue', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (195, 'Tirúa', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (196, 'Alto Bío Bío', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (197, 'Quilaco', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (198, 'Quilleco', 10);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (199, 'Angol', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (200, 'Carahue', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (201, 'Cholchol', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (202, 'Cunco', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (203, 'Curacautín', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (204, 'Freire', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (205, 'Galvarino', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (206, 'Lonquimay', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (207, 'Los Sauces', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (208, 'Lumaco', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (209, 'Melipeuco', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (210, 'Nueva Imperial', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (211, 'Padre Las Casas', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (212, 'Perquenco', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (213, 'Pucon', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (214, 'Saavedra', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (215, 'Temuco', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (216, 'Toltén', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (217, 'Vilcún', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (218, 'Villarrica', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (219, 'Lautaro', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (220, 'Victoria', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (221, 'Loncoche', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (222, 'Curarrehue', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (223, 'Pitrufquen', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (224, 'Gorbea', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (225, 'Teodoro Schmidt', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (226, 'Collipulli', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (227, 'Ercilla', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (228, 'Purén', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (229, 'Traiguén', 11);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (230, 'Valdivia', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (231, 'Corral', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (232, 'Lanco', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (233, 'Los Lagos', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (234, 'Máfil', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (235, 'Mariquina', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (236, 'Paillaco', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (237, 'Futrono', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (238, 'La Unión', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (239, 'Río Bueno', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (240, 'Lago Ranco', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (241, 'Panguipulli', 12);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (242, 'Puerto Montt', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (243, 'Osorno', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (244, 'Ancud', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (245, 'Castro', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (246, 'Puerto Varas', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (247, 'Frutillar', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (248, 'Llanquihue', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (249, 'Calbuco', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (250, 'Puerto Octay', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (251, 'Maullín', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (252, 'Hualaihué', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (253, 'Dalcahue', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (254, 'Curaco de Vélez', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (255, 'Quellón', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (256, 'Queilen', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (257, 'Puqueldón', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (258, 'Quemchi', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (259, 'Puyehue', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (260, 'Cochamó', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (261, 'Futaleufú', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (262, 'Los Muermos', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (263, 'Fresia', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (264, 'San Pablo', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (265, 'San Juan de la Costa', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (266, 'Purranque', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (267, 'Río Negro', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (268, 'Chonchi', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (269, 'Quinchao', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (270, 'Chaitén', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (271, 'Palena', 13);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (272, 'Coyhaique', 14);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (273, 'Aysén', 14);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (274, 'Cisnes', 14);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (275, 'Chile Chico', 14);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (276, 'Rio Ibáñez', 14);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (277, 'Guaitecas', 14);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (278, 'Cochrane', 14);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (279, 'Tortel', 14);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (280, 'O''Higgins', 14);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (281, 'Lago Verde', 14);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (282, 'Punta Arenas', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (283, 'Puerto Natales', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (284, 'Porvenir', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (285, 'Cabo de Hornos', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (286, 'Laguna Blanca', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (287, 'Río Verde', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (288, 'San Gregorio', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (289, 'Timaukel', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (290, 'Antártica', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (291, 'Torres del Paine', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (292, 'Primavera', 15);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (293, 'Santiago', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (294, 'Ñuñoa', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (295, 'Providencia', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (296, 'La Florida', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (297, 'Maipú', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (298, 'Las Condes', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (299, 'Vitacura', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (300, 'Recoleta', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (301, 'Estación Central', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (302, 'Puente Alto', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (303, 'San Bernardo', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (304, 'La Pintana', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (305, 'San Miguel', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (306, 'El Bosque', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (307, 'Cerro Navia', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (308, 'Quilicura', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (309, 'La Reina', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (310, 'Renca', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (311, 'Pudahuel', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (312, 'Lo Prado', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (313, 'Lampa', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (314, 'Colina', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (315, 'Buin', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (316, 'Cerrillos', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (317, 'El Monte', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (318, 'Peñaflor', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (319, 'San José de Maipo', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (320, 'Lo Espejo', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (321, 'La Granja', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (322, 'Huechuraba', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (323, 'Alhué', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (324, 'Melipilla', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (325, 'Paine', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (326, 'Peñalolén', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (327, 'San Ramón', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (328, 'Lo Barnechea', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (329, 'Padre Hurtado', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (330, 'Conchalí', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (331, 'Independencia', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (332, 'La Cisterna', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (333, 'Macul', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (334, 'Pedro Aguirre Cerda', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (335, 'Quinta Normal', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (336, 'San Joaquín', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (337, 'Curacaví', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (338, 'Calera de Tango', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (339, 'Isla de Maipo', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (340, 'Pirque', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (341, 'Talagante', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (342, 'Til Til', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (343, 'María Pinto', 16);
INSERT INTO "public"."gestion_inmuebles_comuna" VALUES (344, 'San Pedro(Metropolitana)', 16);

-- ----------------------------
-- Auto increment value for gestion_inmuebles_comuna
-- ----------------------------
SELECT setval('"public"."gestion_inmuebles_comuna_id_comuna_seq"', 344, true);

-- ----------------------------
-- Indexes structure for table gestion_inmuebles_comuna
-- ----------------------------
CREATE INDEX "gestion_inmuebles_comuna_id_region_id_6f9f46f0" ON "public"."gestion_inmuebles_comuna" USING btree (
  "id_region_id" "pg_catalog"."int4_ops" ASC NULLS LAST
);

-- ----------------------------
-- Primary Key structure for table gestion_inmuebles_comuna
-- ----------------------------
ALTER TABLE "public"."gestion_inmuebles_comuna" ADD CONSTRAINT "gestion_inmuebles_comuna_pkey" PRIMARY KEY ("id_comuna");

-- ----------------------------
-- Foreign Keys structure for table gestion_inmuebles_comuna
-- ----------------------------
ALTER TABLE "public"."gestion_inmuebles_comuna" ADD CONSTRAINT "gestion_inmuebles_co_id_region_id_6f9f46f0_fk_gestion_i" FOREIGN KEY ("id_region_id") REFERENCES "public"."gestion_inmuebles_region" ("id_region") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY DEFERRED;
