/*
 Navicat Premium Data Transfer

 Source Server         : localhost_5432
 Source Server Type    : PostgreSQL
 Source Server Version : 160004 (160004)
 Source Host           : localhost:5432
 Source Catalog        : gestion_inmuebles
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 160004 (160004)
 File Encoding         : 65001

 Date: 10/12/2024 15:38:06
*/


-- ----------------------------
-- Table structure for gestion_inmuebles_tipoinmueble
-- ----------------------------
DROP TABLE IF EXISTS "public"."gestion_inmuebles_tipoinmueble";
CREATE TABLE "public"."gestion_inmuebles_tipoinmueble" (
  "id_tipo_inmueble" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1
),
  "tipo_inmueble" varchar(100) COLLATE "pg_catalog"."default" NOT NULL
)
;

-- ----------------------------
-- Records of gestion_inmuebles_tipoinmueble
-- ----------------------------

-- ----------------------------
-- Auto increment value for gestion_inmuebles_tipoinmueble
-- ----------------------------
SELECT setval('"public"."gestion_inmuebles_tipoinmueble_id_tipo_inmueble_seq"', 1, false);

-- ----------------------------
-- Primary Key structure for table gestion_inmuebles_tipoinmueble
-- ----------------------------
ALTER TABLE "public"."gestion_inmuebles_tipoinmueble" ADD CONSTRAINT "gestion_inmuebles_tipoinmueble_pkey" PRIMARY KEY ("id_tipo_inmueble");
